### ISSUE TITLE
Code run error

### ISSUE THREAD

**Issue by ydxswys1** [hongyizhi/SCLDGN#1]
Hello, I have an error running train.py file after running the preprocessing code.
as follow:

D:\software\anaconda\envs\pytorch\python.exe E:\project\SCLDGN-main\train.py 
E:\project\SCLDGN-main
fetch ssettins:  ../data/bci42a/ 0
All the data you need is present! 
Outputs will be saved in folder : E:\project\SCLDGN-main\output\bci42a\2024-08-11--16-10-42B7\
Data loading in progress
fetch ssettins:  E:\project\SCLDGN-main\..\data\bci42a 0
All the data you need is present! 
Data loading finished
Trainable Parameters in the network are: 874121
Results sequence is train, val , test
[]
[]
[]
[]
[]
[]
Traceback (most recent call last):
  File "E:\project\SCLDGN-main\train.py", line 201, in <module>
    ho(datasetId=0, network='B7', batchSize=32, feature=32, subTorun=[0, 9], dropoutP=0., c=0.5, isProj=True,
  File "E:\project\SCLDGN-main\train.py", line 196, in ho
    save_book(trainResults, valResults, testResults, subs, totalTime, bestEpoch, config, name='results.xls')
  File "E:\project\SCLDGN-main\utils\tools.py", line 106, in save_book
    book.save(os.path.join(config['outPath'], name))
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\xlwt\Workbook.py", line 710, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\xlwt\Workbook.py", line 680, in get_biff_data
    self.__worksheets[self.__active_sheet].selected = True
IndexError: list index out of range

**Comment by hongyizhi** [comment]
please check all the path is right. it seems that "book.save(os.path.join(config['outPath'], name))" is error. check whether config['outPath'] has something wrong

**Comment by hongyizhi** [comment]
@ydxswys1 
please check all the path is right. it seems that "book.save(os.path.join(config['outPath'], name))" is error. check whether config['outPath'] has something wrong

**Comment by ydxswys1** [comment]
In line 114 of train.py:
    for iSub, sub in enumerate(subs):
I print subs directly with the output [], And then I print data.labels, and the output is [].Probably because of line 68:data = eegDataset(dataPath=config['inDataPath'], dataLabelsPath=config['inLabelPath'], preloadData=config['preloadData'],transform=None)

**Comment by ydxswys1** [comment]
When I run train.py, the model does not actually undergo any training and outputs directly, which is why the above error is reported

**Comment by hongyizhi** [comment]
please check whether the code fine the data in line 68. 
Our code references the toolbox (https://github.com/ravikiran-mane/FBCNet) provided by Ravikiran Mane. The toolbox includes an instruction file for reference. In our data processing, we make some extensions based on this toolbox, such as EA processing and the handling of new datasets.
Specifically, the function “fetchData” in train.py, line 66, processes the raw data and stores the processed data locally. 

The data extraction pipeline is as follows: originalData->rawMat->rawPython->multiviewPython.
originalData folder contains the raw data files for a public dataset, typically in .gdf or .mat format. According to the original paper of a given dataset, the function “parse[GivenDataset]Dataset” in saveData.py, divides the raw data into a set of trials and generates labels. The processed data by the function “parse[GivenDataset]Dataset” is then stored as .mat file in the rawMat folder.
The function “matToPython” saves each trial from every .mat file in the rawMat folder as a .npy file in the rawPython folder. Each .npy file in the rawPython folder contains EEG data for a single trial, alone with corresponding label, subject label and session label.
Finally, the function “pythonToMultiviewPython” filters the EEG data from each .npy file using band-pass filters, and saves it to the multiviewPython folder. Therefore, each .npy file in the multiviewPython folder contains band-pass filtered EEG data for a single trial, alone with corresponding label, subject label and session label.

![image](https://github.com/user-attachments/assets/0216e592-8e3c-49f6-9fb3-bc7e50c75108)

**Comment by ydxswys1** [comment]
Yes, I understand that your code references FBCNet or some version of it (e.g. FBMSNet, LightConvNet, TSFCNet, etc.). In fact, your code in the preprocessing fetchData function or pythonToMultiviewPython function gives one less parameter, filterTransform. Moreover, I saw that the paper also mentioned nine Chebyshev Type II bandpass filters spanning from 4 to 40 Hz, which is consistent with FBMSNet. So I copied the FBMSNet code filterTransform = {' filterBank: {' filtBank: [[4, 8], [8, 12], [12 dec], [16], [20, 24], [24, 28], [28], [4 32 ],[36,40]],'fs':250, 'filtType':'filter'}}

**Comment by ydxswys1** [comment]
I haven't changed any code except filterTransform = {' filterBank: {' filtBank: [[4, 8], [8, 12], [12 dec], [16], [20, 24], [24, 28], [28], [4] 32, 40 [36]], 'the fs: 250,' filtType ':' filter '}}

**Comment by hongyizhi** [comment]
i run my code locally again, and there is no any error.
i think you should make sure the data path is right. Because some paths are different from the FCNet (like the data path).
Note that the data is stored in the previous directory of the root directory
just like:

/research
--/data
----/bci42a
------/originalData
--/SCLDGN
----/baseModel
----/dataset
----/lossFunction
----.....
        
Here are the runing results:
.....
Creating python eegdataset with raw data 
Appears that the raw eegdataset data exists but its not converted to multi-view eegdataset yet. Starting this processing
Outputs will be saved in folder : E:\research\SCLDGN\..\data\bci42a\multiviewPython
0% Completed
1% Completed
2% Completed
3% Completed
4% Completed
5% Completed
6% Completed
7% Completed
8% Completed
9% Completed
10% Completed
11% Completed
12% Completed
13% Completed
14% Completed
15% Completed
16% Completed
17% Completed
18% Completed
19% Completed
20% Completed
21% Completed
22% Completed
23% Completed
24% Completed
25% Completed
26% Completed
27% Completed
28% Completed
29% Completed
30% Completed
31% Completed
32% Completed
33% Completed
34% Completed
35% Completed
36% Completed
37% Completed
38% Completed
39% Completed
40% Completed
41% Completed
42% Completed
43% Completed
44% Completed
45% Completed
46% Completed
47% Completed
48% Completed
49% Completed
50% Completed
51% Completed
52% Completed
53% Completed
54% Completed
55% Completed
56% Completed
57% Completed
58% Completed
59% Completed
60% Completed
61% Completed
62% Completed
63% Completed
64% Completed
65% Completed
66% Completed
67% Completed
68% Completed
69% Completed
70% Completed
71% Completed
72% Completed
73% Completed
74% Completed
75% Completed
76% Completed
77% Completed
78% Completed
79% Completed
80% Completed
81% Completed
82% Completed
83% Completed
84% Completed
85% Completed
86% Completed
87% Completed
88% Completed
89% Completed
90% Completed
91% Completed
92% Completed
93% Completed
94% Completed
95% Completed
96% Completed
97% Completed
98% Completed
99% Completed
All the data you need is present! 
Data loading finished
Trainable Parameters in the network are: 874121
Code will be running on device  cuda:0
Results will be saved in folder : E:\research\SCLDGN\output\bci42a\2024-08-11--16-59-34B7\sub0
	 	 Epoch 1
Train loss = 1.199 Train Acc = 0.450 Val Acc = 0.423 Val loss = 1.238 Epoch Time = 24.503

Process finished with exit code -1

And data.labels shows:
![image](https://github.com/user-attachments/assets/02f1b28f-c6fa-464a-a5a2-dea84aa120d7)

**Comment by ydxswys1** [comment]
![1723367479153](https://github.com/user-attachments/assets/2039252a-7ca0-4040-bb23-463ac3c73fd3)
![image](https://github.com/user-attachments/assets/8450699c-566c-4bd9-a642-0aef1a88b0ee)

应该不是路径的问题，那个输出报错倒是小问题，我什么代码都没改，运行完预处理之后，再运行train.py文件，subs，data.labels竟然都是空的列表。应该就是  它的问题，data = eegDataset(dataPath=config['inDataPath'], dataLabelsPath=config['inLabelPath'],
                      preloadData=config['preloadData'], transform=None)。
eegDataset函数是
class eegDataset(Dataset):

    def __init__(self, dataPath, dataLabelsPath, transform=None, preloadData=False):

        self.labels = []
        self.data = []
        self.dataPath = dataPath
        self.dataLabelsPath = dataLabelsPath
        self.preloadData = preloadData
        self.transform = transform

        # Load the labels file
        with open(self.dataLabelsPath, "r") as f:
            eegReader = csv.reader(f, delimiter=',')
            for row in eegReader:
                self.labels.append(row)

            # remove the first header row
            del self.labels[0]

        # convert the labels to int
        for i, label in enumerate(self.labels):
            self.labels[i][2] = int(self.labels[i][2])

        # if preload data is true then load all the data and apply the transforms as well
        if self.preloadData:
            for i, trial in enumerate(self.labels):
                with open(os.path.join(self.dataPath, trial[1]), 'rb') as fp:
                    d = pickle.load(fp)
                    if self.transform:
                        d = self.transform(d)
                    self.data.append(d)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        '''Load and provide the data and label'''

        if self.preloadData:
            data = self.data[idx]

        else:
            with open(os.path.join(self.dataPath, self.labels[idx][1]), 'rb') as fp:
                data = pickle.load(fp)
                if self.transform:
                    data = self.transform(data)

        d = [data[0], data[1]]
        return d

    def createPartialDataset(self, idx, loadNonLoadedData=False):

        self.labels = [self.labels[i] for i in idx]

        if self.preloadData:
            self.data = [self.data[i] for i in idx]
        elif loadNonLoadedData:
            for i, trial in enumerate(self.labels):
                with open(os.path.join(self.dataPath, trial[1]), 'rb') as fp:
                    d = pickle.load(fp)
                    if self.transform:
                        d = self.transform(d)
                    self.data.append(d)
            self.preloadData = True

**Comment by ydxswys1** [comment]
因为，像FBCNet，FBMSNet这些模型的代码我都运行过。预处理肯定不是问题。

**Comment by hongyizhi** [comment]
这个data应该放在scldgn的外面，而不是里面
![image](https://github.com/user-attachments/assets/be089e7a-0071-4e48-bc4a-a06934995098)

**Comment by hongyizhi** [comment]
E:\research\SCLDGN\..\data\bci42a\multiviewPython
注意上我路径的SCLDGN \ ..\data
意思就是data放在了scldgn路径的外面（这一点和其他的代码不一样，我修改过了）
代码报错是因为代码没取到data数据，里面是空的

**Comment by ydxswys1** [comment]
我擦，谢谢佬，刚才没认真看，现在好了。好人一生平安😁

**Comment by ydxswys1** [comment]
下次论文必引用😊

**Comment by 17855457809** [comment]
数据集放到外面为什么依然报错？
